Add Gitadora seeds back to Matixx
zkrising/Tachi pull request #1158
Opened 2024-08-22 06:12 UTC by pfych

2024-08-22 06:15 UTC, pfych commented
+bot diff

2024-08-23 10:05 UTC, zkrising commented
It should be called `nextage`, not `nexage`, no?

2024-08-23 10:06 UTC, zkrising requested changes
`"nexage"` should be called `"nextage"`.

2024-08-24 00:17 UTC, pfych commented
+bot diff

2024-08-27 08:25 UTC, merged