New match type: `ddrSongHash`
zkrising/Tachi pull request #1213
Opened 2024-12-04 13:54 UTC by tranq88

`ddrSongHash` is a 32-character hash used by the official DDR e-amusement website to identify a song.

I believe Tachi supported this match type in the past but I didn't look too much into it. Re-implementing this will allow users to use services that scrape DDR scores from e-amusement, such as 3icecream (however their timestamps can be unreliable; I'm working on my own tool as well).

I tried my best to figure it out without official documentation. If anything's missing, please advise!

2024-12-11 14:29 UTC, zkrising requested changes
Needs some small fixes/justifications before I'm willing to merge, but otherwise looks good. Thank you.

2024-12-11 14:29 UTC, zkrising commented on seeds/scripts/test/match-type.test.ts
> +			// perhaps we could just merge the two "songs" together in the seeds to avoid all this?
This has to be handled specially somehow. If we put this in the seeds like this it's a massive landmine for people to step on!

For now, make both of these charts songHash undefined. We'll come back around to fixing it. Not ideal, but not terrible either.

2024-12-11 14:29 UTC, zkrising commented on server/src/lib/score-import/import-types/common/batch-manual/converter.ts
> +				});
Shouldn't `songHash` be on a SongDocument instead of a ChartDocument? That makes a lot more sense to me.

2024-12-11 14:54 UTC, nyairobi commented
It may be a good idea to mention it in the docs before we forget

* [ddr-SP.md](../blob/main/docs/docs/game-support/games/ddr-SP.md)
* [ddr-DP.md](../blob/main/docs/docs/game-support/games/ddr-DP.md)
* [batch-manual/index.md](../blob/main/docs/docs/codebase/batch-manual/index.md)
* [match-types.md](../blob/main/docs/docs/game-support/common-config/match-types.md)

There are leftover references to the previous `ddrSongHash` implementation, funnily enough

https://github.com/zkrising/Tachi/blob/dc158343d6549977ef42ff22851cc0d96047f4f5/docs/docs/codebase/batch-manual/index.md?plain=1#L75 and https://github.com/zkrising/Tachi/blob/dc158343d6549977ef42ff22851cc0d96047f4f5/docs/docs/codebase/batch-manual/index.md?plain=1#L77

2024-12-18 11:23 UTC, zkrising approved these changes

2024-12-18 12:54 UTC, merged